<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mister Cocktail</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat:300,400">
    <link rel="stylesheet" href="css/cocktails.css">
</head>
<body>
    
    <?php include 'vues/nav.phtml'; ?>
    <?php include 'vues/header.phtml'; ?>

    <!-- DÉBUT DU MAIN -->
    <main>

        <!-- DÉBUT DE LA SECTION LISTE DES COCKTAILS -->
        <section id="add_cocktail" class="mt-5">
            <div class="container">
            <form action="" method="POST" >
                <div class="row">

                        <?php if($message) : ?>
                            <div class="col-12">
                                <div class="alert alert-<?=$messageType?>" role="alert">
                                    <?=$message?>
                                </div>
                            </div>
                        <?php endif; ?>

                        <div class="col-6">
                            
                            <!-- FORMULAIRE ICI -->
                            <div class="mb-3">
                                <label for="name" class="form-label">Nom de l'ingrédient</label>
                                <input type="text" class="form-control" id="name" name="name" placeholder="Citron vert" value="<?=$name?>" required>
                            </div>
                 
                            <div class="mb-3 text-end">
                                <input type="submit" value="Enregistrer" class="btn btn-primary">
                            </div>
                                                        
                        </div>

                    </div>
                </form>
            </div>
        </section>
        <!-- FIN DE LA SECTION LISTE DES COCKTAILS -->
        
    </main>
    <!-- FIN DU MAIN -->
    
    <?php include 'vues/footer.phtml'; ?>


    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.5/dist/umd/popper.min.js" integrity="sha384-Xe+8cL9oJa6tN/veChSP7q+mnSPaj5Bcu9mPX5F5xIGE0DVittaqT5lorf0EI7Vk" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.min.js" integrity="sha384-ODmDIVzN+pFdexxHEHFBQH3/9/vQ9uori45z4JjnFsRydbmQbmL5t1tQ0culUzyK" crossorigin="anonymous"></script>    
</body>
</html>