<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mister Cocktail</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat:300,400">
    <link rel="stylesheet" href="css/cocktails.css">
</head>
<body>

    <?php include 'vues/nav.phtml'; ?>
    <?php include 'vues/header.phtml'; ?>

    <!-- DÉBUT DU MAIN -->
    <main class="mt-5">

        <!-- DÉBUT SECTION DETAIL D'UN COCKTAIL -->
        <section id="detail-cocktail">
        <div class="container">
            <div class="row">
                <div class="col-6">
                    <img src="images/cocktails/<?=$cocktail['image']?>" alt="" class="img-fluid">
                </div>
                <div class="col-6">
                    <h2><?=$cocktail['name']?></h2>
                    <h3>Famille&nbsp;: <?=$cocktail['family_name']?></h3>
                    <p><?=$cocktail['description']?></p>
                    <h4>Prix moyen&nbsp;: <?=$cocktail['price']?>€</h4>
                    <h4>Année d'invention&nbsp;: <?=$cocktail['year']?></h4>
                    <h4>Ingrédients&nbsp;</h4>
                    <ul>
                        <?php foreach($ingredients as $ingredient) : ?>
                            <li><?=$ingredient['name']?></li>
                        <?php endforeach; ?>
                    </ul>
                </div>
            </div>
        </div>
        
        </section>
        <!-- FIN SECTION DETAIL D'UN COCKTAIL -->
        
    </main>
    <!-- FIN DU MAIN -->
    
    <?php include 'vues/footer.phtml'; ?>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.5/dist/umd/popper.min.js" integrity="sha384-Xe+8cL9oJa6tN/veChSP7q+mnSPaj5Bcu9mPX5F5xIGE0DVittaqT5lorf0EI7Vk" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.min.js" integrity="sha384-ODmDIVzN+pFdexxHEHFBQh4/9/vQ9uori45z4JjnFsRydbmQbmL5t1tQ0culUzyK" crossorigin="anonymous"></script>    
</body>
</html>